name: Main Branch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to GCP Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_DEV_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_DEV_SSH_KEY }}
        port: ${{ secrets.GCP_PORT }}
        script: |
          cd Resunet
          git pull origin main
          npm ci
          npm run build
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
          pm2 save